name: Semgrep and Secret Scan

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "20 17 * * *"

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-oss-scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Semgrep
        run: semgrep scan --config auto --error

  gitleaks:
    name: gitleaks-secrets
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
